src/app/(dashboard)/dashboard/page.tsx, src/app/api/stripe/checkout/route.ts, src/app/api/stripe/webhook/route.ts
Vercel develop deployment continues to fail during build, so many console.logs added to api/stripe/checkout (file flagged in Vercel) to catch issue. Note: this PR exists for record, and to trigger develop deployment in Vercel.
Other updates:
-auth flow locally tested again and Stipe user payment redirected user to /subscribe page (instead of /dashboard page for paid user)
-updates to api/stripe/webhook and /dashbaord/page.tsx should fix this.
=> merge epic/authflow > develop: largely testing for Vercel develop environment

src/app/api/playlists/[id]/route.ts, src/app/api/playlists/[id]/videos/route.ts, src/app/api/playlists/route.ts
See Google doc for routes, necessary Headers, and JSON body requirements for POST/PATCH:
url: https://docs.google.com/document/d/1V7WW1DN3H9w0xyveZHcsYUZSwY0F9fAAeohQTZibsVc/edit?tab=t.0#heading=h.tkouraj1fo6p
All routes tested up to these NOT included routes:
DELETE   /api/playlists/[id]/videos/[video_id]    (delete video from playlist)
PATCH   /api/playlists/[id]/videos/[video_id]   (change 'position' property of video to change what order it should be in)
=> add playlists API routes

src/app/api/playlists/[id]/route.ts, src/app/api/playlists/[id]/videos/[video_id]/route.ts, src/app/api/playlists/[id]/videos/route.ts
- /api/playlists/[id]/videos/[video_id] --  added allowing for DELETE and PATCH operations
- src/app/api/playlists/[id]/route.ts -- modified to ensure that if a playlist is deleted from playlist table in db, data is also deleted about that playlist from associated db tables (sp. playlist_videos)
- src/app/api/playlists/[id]/videos/route.ts -- updated to make sure duplicate videos cannot be added to a playlist; also ensure video id is strictly numeric
=> add route to delete video(s) from playlist or modify video position; optimizations for other routes

src/app/(dashboard)/dashboard/profile/page.module.scss, src/app/(dashboard)/dashboard/profile/page.tsx, src/components/layout/Header/Header.module.scss, src/components/layout/Header/Header.tsx, src/components/ui/Button/Button.module.scss, src/components/ui/Button/Button.tsx, src/styles/globals.scss
This PR updates the **Profile Page** with significant improvements in UI, form validation, API integration placeholders, and better button placement.
---
- **Positioning of Buttons:**  
- Moved **"Cancel"** & **"Save Profile"** buttons **below the input fields** for a more intuitive layout.  
- Ensured spacing aligns with existing design patterns.  
- **Styling Enhancements:**  
- Unified **input field styling** to match global styles (`globals.scss`).  
- Maintained **consistent button variants** using `Button` component.  
- **Logout Button:**  
- Now utilizes the **same logout logic as the logout button originally in header** for consistency.  
- **Email Validation:**  
- Ensured input follows **correct email format** before allowing submission.  
- **Password Requirements:**  
- …
=> Feature/member profile betty [WIP - mobile front-end]

src/app/(dashboard)/dashboard/cancel-subscription/page.module.scss, src/app/(dashboard)/dashboard/cancel-subscription/page.tsx, src/app/(dashboard)/dashboard/profile/page.module.scss, src/app/(dashboard)/dashboard/profile/page.tsx, src/app/(dashboard)/dashboard/subscribe/page.module.scss, src/app/(dashboard)/dashboard/subscribe/page.tsx, src/app/api/stripe/cancel-subscription/route.ts, src/app/api/stripe/webhook/route.ts
-flow tested in deployed development branch confirming Stripe webhooks work when signing up for new account and purchasing plan (via Stripe test environment)
-added functionality and minimal styling for cancellation page allowing user to cancel subscription (linked from user profile)
-added minimal styling to subscribe page for users without paid account
=> new file additions and file updates to allow user to cancel subscription

src/app/api/stripe/cancel-subscription/route.ts
-cancel subscription failed in deployed develop branch with error related to cancel-subscription route
-updated code to test again
=> fix, cancel-subscription route through error in deployed version, updated code to retest

src/app/api/stripe/cancel-subscription/route.ts
fix v2, update to incorrectly named import from lib/auth.ts helper file
=> fix v2, update to incorrectly named import from lib/auth.ts helper file

src/app/api/stripe/cancel-subscription/route.ts
fix V3, updated code b/c errors were being thrown related to failing to properly extract auth token
=> fix V3, updated code b/c errors were being thrown related to failing to properly extract auth token

src/app/api/stripe/cancel-subscription/route.ts
cancellation happens now via cancel-subscription route along with db uupdate, functions related to this in webhook become backup
=> fix, cancellation happens now via cancel-subscription

src/app/api/stripe/cancel-subscription/route.ts, src/app/api/stripe/webhook/route.ts
fix, cancellation works, but was not accounting for user being able to maintain their subscription until billing period ends before being locked out after cancelling
=> fix, cancellation works, but was not accounting for having app until billing period ends

src/app/api/stripe/webhook/route.ts
fix, last update broke update to database showing is_paid_user = 1 when new users sign up (after testing in deployed dev env.)"
=> fix, last update broke update to database showing is_paid_user = 1 

src/app/api/stripe/webhook/route.ts
modified again to fix broken is_paid_user issue with addition of cancellation
=> fix, another fix to correct for db not updating is_paid_user from 0 to 1

src/app/api/stripe/webhook/route.ts
-fix, continuing to troubleshoot issue pertaining to Webhook verification, needs to be tested in live environment
=> fix, continuing to troubleshoot issue pertaining to Webhook verification

src/app/api/stripe/webhook/route.ts
logging, adding extra logs to stripe/webhook to troubleshoot server issue not updating paid user
=> logging, adding extra logs to stripe/webhook to troubleshoot server issue not updating paid user

src/app/api/stripe/webhook/route.ts
updated stripe webhook to use Object.fromEntries() to extract stipe signature
=> updated stripe webhook to use Object.fromEntries() 

src/app/api/stripe/webhook/route.ts
udpate /stripe/webhook/ with more robust logging and attempt to match stripe-signature based on version
=> udpate /stripe/webhook/ with more robust logging and attempt to match stripe-signature based on version

src/app/api/stripe/cancel-subscription/route.ts, src/app/api/stripe/checkout/route.ts
updated all stripe API routes to use apiVersino 2023-10-16 as configured in Stripe dashboard related to /api/stripe/webhook; checkout using different apiVersion in previous commit so possible stripe-signature mismatch
=> updated all stripe API routes to use apiVersino 2023-10-16

src/app/api/stripe/webhook/route.ts
update stripe webhook file with more robust error handling to check why stripe-signature possibly has mismatch
=> update stripe webhook file with more robust error handling

src/pages/api/stripe/webhook.ts
update stripe webhook (confirmed working live) to make sure updates db for is_paid_use and allows user to have cancel period related to when the cancel
=> update stripe webhook route

src/app/(dashboard)/dashboard/playlistplayer/[playlist_id]/page.module.scss, src/app/(dashboard)/dashboard/playlistplayer/[playlist_id]/page.tsx
Merge feature/member-responsive-betty with current develop branch updates
resolve merge conflicts
=> Merge feature/member-responsive-betty with current develop branch updates

src/app/api/stripe/cancel-subscription/route.ts
update 2, ensure if someone starts free trial and they want to cancel before they are charged (during trial membership) they can do so
=> update 2, ensure membership can be cancelled during free tiral

src/app/(dashboard)/dashboard/[continuous_video_name]/[continuous_video_id]/videos/page.tsx, src/app/(dashboard)/dashboard/library/[playlist_id]/page.tsx, src/components/pages/dashboard/Video/Video.tsx
-code updated to utilize newly seeded 'duration' field from chapters API route
-cleaned up a some files removing unneeded console.logs
=> update code to utilize fixed duratino property on chapters API route

.github/workflows/deploy-preview.yaml
additional pipeline testing needed
.yaml file configuration failed on previous deploy and did not cause triggered deployment to staging environment
also, webhook configurations removed from Vercel and Github as they were causing unwanted deployments of multiple environments
=> update .yaml file to retest (last test failed); simplified version with less Vercel related variables

.github/workflows/deploy-preview.yaml
.yaml file updated b/c previous merge from develop to staging did not trigger deployment
=> Testing pipeline deployment trigger deploying develop to staging

src/components/pages/homepage/Testimonials/Testimonials.tsx
-testing Vercel pipeline
-previous test Vercel Branch tracking setting was not properly toggled off
--resulted in merge to develop triggering deployment's to both develop and Preview environments in Vercel
=> update homepage testimonial first sentence to trigger deployment; small change made testing Vercel pipeline

.github/workflows/deploy-to-vercel-develop-env.yaml, .github/workflows/deploy-to-vercel-preview-env.yaml
testing Vercel pipeline with newly corrected Vercel flag --target (in both .yaml files)
=> fix, incorrect flag names in both .yaml files; --environment become --target

.github/workflows/deploy-to-vercel-develop-env.yaml, .github/workflows/deploy-to-vercel-preview-env.yaml
-previous trigger of deployment to Vercel failed b/c of .yaml file error; logs indicate -'-yes' flag was missing
- '--yes' flag added to both .yaml files
=> fix, add --yes flag to both .yaml files

.github/workflows/deploy-to-vercel-develop-env.yaml, .github/workflows/deploy-to-vercel-preview-env.yaml
-previous .yaml through errors related to need to build project locally before deploying and using --prebuilt flag
-Build Project job added to resolve this (in both .yaml files)
=> update both .yaml files to include Build Project job

.github/workflows/deploy-to-vercel-develop-env.yaml, .github/workflows/deploy-to-vercel-preview-env.yaml, src/app/api/stripe/checkout/route.ts, src/pages/api/stripe/webhook.ts
-Stripe checkout succeeded in production to process payment, but /pages/api/webhook API route failed (so is_paid_user not working in production)
-added console.logs and logic to see why there's an error that Stripe signature in headers does not match what it expects
-also testing not using .yaml files (commented out for now), and modifying CI/CD Vercel flow
NOTE: 
-updated in this branch debug/stripe-checkout-production-failure need to move from:
feature > develop
develop > stating 
staging > production
=> Debug Stripe webhook in productino

src/app/(dashboard)/dashboard/context/PlaylistContext.tsx, src/app/(dashboard)/dashboard/page.tsx, src/app/(dashboard)/dashboard/player/[continuous_vimeo_id]/page.tsx, src/app/(dashboard)/dashboard/playlistplayer/[playlist_id]/page.tsx, src/app/api/continuous-videos/[id]/continuous-video/route.ts, src/components/pages/dashboard/AddPlaylistModal/AddPlaylistModal.tsx, src/components/pages/dashboard/PlaylistPlayerVideos/PlaylistPlayerVideos.tsx, src/components/pages/dashboard/SortablePlaylistPlayerVideo/SortablePlaylistPlayerVideo.tsx, src/components/pages/dashboard/Video/Video.tsx, src/components/pages/dashboard/VideoList/VideoList.module.scss, src/components/pages/dashboard/VideoList/VideoList.tsx, src/components/pages/library/LibraryPageContent/LibraryPageContent.tsx, src/components/pages/library/PlayListCard/PlayListCard.tsx, src/lib/email.ts
-known issue that needs resolving ... unable to delete video form playlist via AddModal
=> Merging 4/1 fixes with updates to library styling

src/components/pages/dashboard/AddPlaylistModal/AddPlaylistModal.tsx
-delete functionality for AddPlaylistModal needed to utilize 'id' from /ap/playlists/<playlist-id> to match what the API route expected (was using vimeo_video_id prior) ....  vimeo_video_id  matched to 'id' from ap/playlists/<playlist-id> and used in delete route (confirmed to work)
=> updated delete functionality in AddPlaylistModal 

src/components/pages/dashboard/AddPlaylistModal/AddPlaylistModal.tsx
-fix build failure related to Next.js / typescript
=> fix build error in AppPlaylistModal

src/components/pages/homepage/HomeHero/HomeHero.tsx
upon request, remove 'finess' from video hero
=> upon request, remove 'finess' from video hero

src/app/(dashboard)/dashboard/[continuous_video_name]/[continuous_video_id]/videos/page.module.scss, src/app/(dashboard)/dashboard/[continuous_video_name]/[continuous_video_id]/videos/page.tsx, src/app/(dashboard)/dashboard/playlistplayer/[playlist_id]/page.tsx, src/components/pages/dashboard/VideoList/VideoList.tsx, src/components/pages/library/PlayListCard/PlayListCard.module.scss, src/components/pages/library/PlayListCard/PlayListCard.tsx, src/utils/parseDescription.ts
update prescription video titles and descriptions based on updated title plus description format (remove bullets using stars)
=> update prescription video titles and descriptions

src/app/(marketing)/the-workout/page.tsx, src/components/pages/homepage/About/About.module.scss, src/components/pages/homepage/About/About.tsx
update styling in About UI component on homepage not rendering properly; update copy for workouts page
=> update styling in About UI component on homepage not rendering properly

src/app/(dashboard)/dashboard/profile/page.module.scss, src/app/(dashboard)/dashboard/profile/page.tsx, src/components/ui/Button/Button.module.scss
add missed additions to last push effecting profile button and justify-content: center; for Button component styling
=> add missed additions to last push effecting profile button and Button component

src/app/(marketing)/contact/page.module.scss, src/app/(marketing)/contact/page.tsx, src/components/pages/contact/Accordion/Accordion.module.scss, src/components/pages/contact/Accordion/Accordion.tsx
=> update contact page (FAQ) with first round copy; modify styling

src/app/(dashboard)/dashboard/subscribe/page.tsx
correct link on /subscribe page Main Site link was going to wrong apage
=> correct link on /subscribe page Main Site link was going to wrong page

src/app/account/profile/page.tsx, src/utils/inputUtils.ts
-upodated so toats notifcations appear on success
-toast notification appears if user enters age under 13
-gender update to conform with expected DB values that should be male, female, non-binary, prefer not  to say
=> update profile page so toaster notification work, and feedback for under age users provided

src/app/(dashboard)/dashboard/library/page.module.scss, src/app/(dashboard)/dashboard/library/page.tsx, src/app/(dashboard)/dashboard/page.module.scss, src/app/(dashboard)/dashboard/page.tsx, src/components/pages/dashboard/Navigation/Navigation.module.scss, src/components/pages/dashboard/Navigation/Navigation.tsx
-ensure header with 'S' still exists in upper left of dashbaord
-update Navigate and header to uesr large 'S' icon in upper left
-correct issues causing 'header' area to not fully cover mai n page content when scrolling down page
=> Update navigate area and 'header' area in dahsboard

src/app/(dashboard)/dashboard/player/[continuous_vimeo_id]/page.module.scss, src/app/(dashboard)/dashboard/player/[continuous_vimeo_id]/page.tsx, src/components/pages/dashboard/SortableVideoCard/SortableVideoCard.tsx, src/components/pages/dashboard/Video/Video.tsx
-on browser page, trim Prescription program 1 so does not have title like: upper body bands rd. 1: pyramid stance and only has upper body bands rd. 1
-change rd. to round on all non video player pages
-update video player page so title and description near video player delay 1 second (so doesn't show these details on prescription pages when Warmup starts videos and first video title and details flash quickly)
=> update titles of videos

src/components/pages/library/DeletePlaylistModal/DeletePlaylistModal.tsx, src/components/pages/library/EditPlaylistModal/EditPlaylistModal.tsx
update DeletePlaylistModal and EditPlaylist modal so use createPortal() to render modal via modal-root div at document level in /app/layout.tsx
=> update DeletePlaylistModal and EditPlaylist modal so use createPortal

src/components/pages/homepage/Testimonials/Testimonials.tsx
-include 8 testimonials
-limit text of testimonials to 300 characters
=> fix #1 - update testimonials to 8 

src/components/pages/homepage/Testimonials/Testimonials.tsx
updated Testimonails truncate function to only cut off at end of sentence with '.'
=> updated Testimonail's truncate function

src/app/(auth)/auth/forgot-password/page.module.scss, src/app/(auth)/auth/forgot-password/page.tsx, src/app/(auth)/auth/login/page.module.scss, src/app/(auth)/auth/login/page.tsx, src/app/(auth)/auth/signup/page.module.scss, src/app/(auth)/auth/signup/page.tsx
update auth pages so loading state button text is also white
=> update auth loading state button text

src/app/(auth)/auth/forgot-password/page.tsx, src/app/(auth)/auth/login/page.tsx, src/app/(auth)/auth/signup/page.tsx
corrections to BEM names in certain auth pages preventing styling from working on button text
=> correcting auth page class name error

src/app/(auth)/auth/signup/page.module.scss
.scss update for signup correcting button text issue
=> styling correction for signup page button text

src/app/(auth)/auth/login/page.module.scss
make Sign up text bold in login page by using important
=> make Sign up text bold in login page by using important

src/app/layout.tsx
add meta tag in /app/layout.tsx detailing release verion
=> add meta tag in /app/layout.tsx detailing release verion

src/components/pages/homepage/HomeHero/HomeHero.tsx
HomeHero.tsx update; useEffect() code added to handle managing hero video playing to resolve issue of video not loading without refresh in Meta environment (from IG link)
=> HomeHero.tsx update; useEffect() code added to handle managing hero video autoplay
